# Generated by Django 4.0.5 on 2022-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='obstacles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
